sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t kaankarakoc/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true kaankarakoc/docker-react npm run test